import '../modelos/receita.dart';

final List<Recipe> mockRecipes = [
  Recipe(
    id: 'mock_1',
    title: 'Frango ao Limão Siciliano',
    titleEn: 'Lemon Chicken',
    query: 'Frango ao Limão Siciliano',
    createdAt: DateTime(2026, 4, 1),
    time: '35 min',
    servings: '4 porções',
    difficulty: 'Médio',
    rating: 4.8,
    emoji: '🍋',
    colorStart: '#FFF3C4',
    colorEnd: '#FFD980',
    category: 'Carnes',
    ingredients: [
      '500g de frango',
      '2 limões sicilianos',
      '3 dentes de alho',
      '3 colheres de azeite',
      'Tomilho fresco',
      'Sal e pimenta a gosto',
    ],
    steps: [
      'Tempere o frango com sal, pimenta e alho picado.',
      'Grelhe em fogo médio por 8 min de cada lado.',
      'Adicione o suco de limão e o tomilho.',
      'Finalize com um fio de azeite e sirva quente.',
    ],
  ),
  Recipe(
    id: 'mock_2',
    title: 'Risoto de Cogumelos',
    titleEn: 'Mushroom Risotto',
    query: 'Risoto de Cogumelos',
    createdAt: DateTime(2026, 4, 2),
    time: '45 min',
    servings: '2 porções',
    difficulty: 'Médio',
    rating: 4.9,
    emoji: '🍄',
    colorStart: '#E8D5C4',
    colorEnd: '#C9A882',
    category: 'Massas',
    ingredients: [
      '300g de arroz arbóreo',
      '200g de cogumelos Paris',
      '1 cebola média',
      '½ xícara de vinho branco seco',
      '1L de caldo de legumes quente',
      '50g de parmesão ralado',
    ],
    steps: [
      'Refogue a cebola picada no azeite até ficar transparente.',
      'Adicione o arroz e toste por 2 minutos.',
      'Despeje o vinho e mexa até evaporar.',
      'Adicione o caldo aos poucos, mexendo sempre.',
      'Finalize com os cogumelos e o parmesão.',
    ],
  ),
  Recipe(
    id: 'mock_3',
    title: 'Tacos de Carnitas',
    titleEn: 'Pork Tacos',
    query: 'Tacos de Carnitas',
    createdAt: DateTime(2026, 4, 3),
    time: '2h',
    servings: '6 porções',
    difficulty: 'Difícil',
    rating: 4.7,
    emoji: '🌮',
    colorStart: '#FFE0C4',
    colorEnd: '#FFC080',
    category: 'Outros',
    ingredients: [
      '1kg de pernil suíno',
      '12 tortillas de milho',
      'Coentro fresco',
      '1 cebola roxa',
      '2 limões',
      'Cominho e páprica',
    ],
    steps: [
      'Tempere a carne com cominho, páprica e sal.',
      'Cozinhe em fogo baixo por 2 horas até ficar macia.',
      'Desfie a carne e doure na frigideira por 5 min.',
      'Monte os tacos com cebola, coentro e suco de limão.',
    ],
  ),
  Recipe(
    id: 'mock_4',
    title: 'Smoothie de Açaí',
    query: 'Smoothie de Açaí',
    createdAt: DateTime(2026, 4, 4),
    time: '10 min',
    servings: '2 porções',
    difficulty: 'Fácil',
    rating: 4.6,
    emoji: '🫐',
    colorStart: '#D4B0E8',
    colorEnd: '#9B6FC0',
    category: 'Bebidas',
    ingredients: [
      '200g de açaí congelado',
      '1 banana prata',
      '½ xícara de leite de coco',
      '1 colher de mel',
      'Granola para decorar',
    ],
    steps: [
      'Bata o açaí com a banana no liquidificador.',
      'Adicione o leite de coco e bata mais 30 segundos.',
      'Despeje no copo e finalize com granola e mel.',
    ],
  ),
  Recipe(
    id: 'mock_5',
    title: 'Pão de Queijo Mineiro',
    titleEn: 'Cheese Bread',
    query: 'Pão de Queijo Mineiro',
    createdAt: DateTime(2026, 4, 5),
    time: '25 min',
    servings: '20 unidades',
    difficulty: 'Fácil',
    rating: 5.0,
    emoji: '🧀',
    colorStart: '#FFF8DC',
    colorEnd: '#F5D769',
    category: 'Lanches',
    ingredients: [
      '500g de polvilho azedo',
      '200g de queijo meia-cura ralado',
      '3 ovos',
      '1 xícara de óleo',
      '1 xícara de leite morno',
      'Sal a gosto',
    ],
    steps: [
      'Misture o polvilho com o sal.',
      'Adicione o leite quente e misture bem.',
      'Incorpore os ovos, o óleo e o queijo.',
      'Modele as bolinhas e asse a 200°C por 20 min.',
    ],
  ),
  Recipe(
    id: 'mock_6',
    title: 'Moqueca de Camarão',
    titleEn: 'Prawn Moqueca',
    query: 'Moqueca de Camarão',
    createdAt: DateTime(2026, 4, 6),
    time: '50 min',
    servings: '4 porções',
    difficulty: 'Médio',
    rating: 4.8,
    emoji: '🦐',
    colorStart: '#FFE4C0',
    colorEnd: '#FF9E5E',
    category: 'Outros',
    ingredients: [
      '500g de camarão limpo',
      '400ml de leite de coco',
      '2 tomates picados',
      '1 pimentão vermelho',
      'Coentro fresco',
      '2 colheres de azeite de dendê',
    ],
    steps: [
      'Marine o camarão com limão e sal por 15 min.',
      'Refogue tomate e pimentão no azeite de dendê.',
      'Adicione o leite de coco e deixe ferver.',
      'Acrescente o camarão e cozinhe por 8 min.',
      'Finalize com coentro e sirva com arroz.',
    ],
  ),
];

const List<Map<String, String>> mockCategories = [
  {'id': 'all', 'label': 'Todos', 'emoji': '✨'},
  {'id': 'Carnes', 'label': 'Carnes', 'emoji': '🥩'},
  {'id': 'Massas', 'label': 'Massas', 'emoji': '🍝'},
  {'id': 'Bebidas', 'label': 'Bebidas', 'emoji': '🥤'},
  {'id': 'Lanches', 'label': 'Lanches', 'emoji': '🥪'},
  {'id': 'Doces', 'label': 'Doces', 'emoji': '🍰'},
];

final List<Map<String, dynamic>> mockCommunityPosts = [
  {
    'id': 'cp_1',
    'user': 'Ana Lima',
    'time': '2h',
    'emoji': '🍕',
    'title': 'Minha pizza de massa madre ficou perfeita!',
    'imageSearchEn': 'Margherita Pizza',
    'likes': 142,
    'comments': 23,
    'colorStart': '#FFDED6',
    'colorEnd': '#FF9A85',
  },
  {
    'id': 'cp_2',
    'user': 'Carlos Motta',
    'time': '5h',
    'emoji': '🎂',
    'title': 'Bolo de chocolate de aniversário — receita da vovó',
    'imageSearchEn': 'Chocolate Cake',
    'likes': 89,
    'comments': 15,
    'colorStart': '#D4B0E8',
    'colorEnd': '#9B6FC0',
  },
  {
    'id': 'cp_3',
    'user': 'Mariana Souza',
    'time': '1d',
    'emoji': '🥗',
    'title': 'Salada tailandesa com amendoim — leve e deliciosa',
    'imageSearchEn': 'Thai Green Curry',
    'likes': 67,
    'comments': 8,
    'colorStart': '#C8F7C5',
    'colorEnd': '#82E085',
  },
  {
    'id': 'cp_4',
    'user': 'Pedro Alves',
    'time': '2d',
    'emoji': '🍜',
    'title': 'Ramen caseiro levou 6 horas mas valeu demais!',
    'imageSearchEn': 'Ramen',
    'likes': 201,
    'comments': 44,
    'colorStart': '#FFE0A0',
    'colorEnd': '#FFC040',
  },
];


